In [1]:
import numpy as np

from modules import umatpy
from modules import globpy

In [2]:
''' MATERIAL PROPERTIES '''

##### Penalty parameter (0) #####
K = 1000000000000.0 # 1000.0
##### Isotropic matrix (1-3) #####
C10 = 0.0 # 0.0
C01 = 0.0 # 0.0
PHI = 1.0 # Filament volume fraction 1.0
###### Single Filament (4-11) #####
L = 1.96 # Filament contour length [microm] 1.96
R0F = 1.63 # Filament initial end-to-end distance [microm] 1.63
R0C = 0.014 # CL initial end-to-end distance [microm] 0.014
ETA = 0.5 # CL stiffness [0,1] 0.6666
MU0 = 11111111111111111111111138600.0 # Stretch modulus [pN] inf
BETA = 0.5 # 0.5
B0 = 294.0*16.0*1.38065e-5 # Bending stiffness (T*Lp*kb) [pN * microm**2] 294.0*16.0*1.38e-5
LAMBDA0 = 1.00 # Pre-stretch 1.00
##### Affine Network (12-13) #####
n = 7.66 # Isotropic filaments per unit volume [microm**-3] 7.66
B = 0.001 # Dispersion parameter 0.001

base_material_properties = [K,
    C10, C01, PHI,
    L, R0F, R0C, ETA, MU0, BETA, B0, LAMBDA0,
    n, B
]

In [11]:
seed = 0
np.random.seed(seed)

# Random deformation gradient
F = np.random.rand(3, 3)

# Uniaxial deformation gradient
stretch = 1.15#np.random.uniform(1.0, 1.3)
F_uni = np.array([[stretch, 0.0, 0.0],
              [0.0, 1.0/np.sqrt(stretch), 0.0],
              [0.0, 0.0, 1.0/np.sqrt(stretch)]])
print(f"Random F: {F}")
print(f"Uniaxial F: {F_uni}")

Random F: [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
Uniaxial F: [[1.15       0.         0.        ]
 [0.         0.93250481 0.        ]
 [0.         0.         0.93250481]]


In [16]:
stress = umatpy.run_umat_py(base_material_properties, F_uni, [0.1, 0.8], 0.4, 6)
# print("Stress:", stress)

   1.1499999999999999        0.0000000000000000        0.0000000000000000        0.0000000000000000       0.93250480824031379        0.0000000000000000        0.0000000000000000        0.0000000000000000       0.93250480824031379     

   4.0416113206846171       -2.3220458590333783       -1.7195654616512381        0.0000000000000000        0.0000000000000000        0.0000000000000000     

  -1.86951276E-18   59.2759552      -1.69655881E-18   59.2759552      -1.70549360E-18   59.2759552       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000      -1.69655881E-18   59.2759552      -1.77883764E-18   59.2759552      -1.76693865E-18   59.2759552       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000      -1.70549360E-18   59.2759552      -1.76693865E-18   59.2759552      -1.76096806E-18   59.2759552       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.000000